apiVersion: v1
kind: Service
metadata:
  name: restbet
spec:
  type: NodePort
  selector:
    app: restbet
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30000
    protocol: TCP
